---
#################################################
################## Deployments ##################
#################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.db.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.localPort.db }}
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.postgresPassword }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.localPort.db }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ExportPort.db }}
      targetPort: {{ .Values.localPort.db }}
  selector:
    app: db
