---
#################################################
################## Deployments ##################
#################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repositoryRedis }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.localPort.redis }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.localPort.redis }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3



---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ExportPort.redis }}
      targetPort: {{ .Values.localPort.redis }}
  selector:
    app: redis
